import Head from 'next/head'
import { useAuth } from '../utils/AuthUserContext'
import { withProtected } from '../utils/withAuth'



const Home = () => {

  const { authUser, loading } = useAuth()


  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {!loading && <h1>{JSON.stringify(authUser, null, 4)}</h1>}
      </div>
    </div>

  )
}

export default withProtected(Home)
