import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={'/SignUp'} passHref>
          <button>Sign Up</button>
        </Link>
        <Link href={'/SignIn'} passHref>
          <button>Sign In</button>
        </Link>
      </main>
    </div>
  )
}
